version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "rodrigosantiag"
    open-pull-requests-limit: 10
    target-branch: "develop"
    vendor: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "rodrigosantiag"
    open-pull-requests-limit: 10
    target-branch: "develop"
