services:
  - mysql:5.7
variables:
  MYSQL_ROOT_PASSWORD: "knopix"

before_script:
  - ruby -v
  - mysql --version
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load

rspec:
  stage: test
  script:
    - bundle exec rspec
