test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - gem install bundler
    - bundle install --path /cache
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec spring rspec

staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=binary-financial-system-api --api-key=ee7e5536-218b-40eb-b80d-4e0a084f3d4e
  only:
    - master