services:
  - mysql:latest
variables:
  MYSQL_ROOT_PASSWORD: "knopix"

before_script:
  - sudo apt-get install -y mysql-server mysql-client libmysqlclient-dev
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - RAILS_ENV=test bundle exec rake db:create db:schema:load

rspec:
  stage: test
  script:
    - bundle exec rspec
