services:
  - mysql:latest
variables:
  MYSQL_ROOT_PASSWORD: "knopix"

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  stage: test
  script:
    - bundle exec rspec
