services:
  database:
    image: postgres
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  mailcatcher:
    container_name: mailcatcher
    restart: on-failure:10
    image: stpaquet/alpinemailcatcher:latest
    environment:
      - MAIL_LIMIT=70 # docker image default is 50
    ports:
      - "1080:1080"
      - "1025:1025"
  api:
    build:
      target: development
      context: .
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - mailcatcher

volumes:
  db:
