name: Deploy
run-name: Deploy application
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: trades-management-repo
          IMAGE_TAG: ${{ github.sha }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABSE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Build Docker container and
          # push it to ECR so that it can
          # be deployed to ECS
          docker build . --file Dockerfile --target production --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg DATABASE_URL=$DATABASE_URL --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "{image}::{$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Migration task definition
        id: migration-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/migrations.json
          container-name: trades-management-repo
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy migration to Amazon ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.migration-task-def.outputs.task-definition }}
          service: trades-management-api-service
          cluster: trades-management-cluster
          wait-for-service-stability: true
